#pragma once

#define VFX_API

#ifndef JSON_ENABLE_JSON5
#define JSON_ENABLE_JSON5 1
#endif	//JSON_ENABLE_JSON5

#if JSON_ENABLE_JSON5
#define JSON5_ENABLE_COMMENTS	1
#else
#endif	//JSON_ENABLE_JSON5

/* #undef JSON_ENABLE_DEBUG_WALKER */
#define JSON_ENABLE_DOM_WALKER 1
#define JSON_ENABLE_SIMD_PARSER 1
