#pragma once

#define VFX_API

#ifndef JSON_ENABLE_JSON5
/* #undef JSON_ENABLE_JSON5 */
#endif	//JSON_ENABLE_JSON5

#if JSON_ENABLE_JSON5
#define JSON5_ENABLE_COMMENTS	
#else
#endif	//JSON_ENABLE_JSON5

/* #undef JSON_ENABLE_DEBUG_WALKER */
#define JSON_ENABLE_DOM_WALKER 1
/* #undef JSON_ENABLE_SIMD_PARSER */
